---
environment: {GIT_LFS_SKIP_SMUDGE: '1', STACK_ROOT: /drone/workspace/.stack}
kind: pipeline
name: juvix-ci-build-pr
node: {project: juvix}
steps:
- commands: [echo "e3420e6c66604c53d26292db4a2ba4130d017db1b2e9652d796410e4a9305a04  Makefile"
      | sha256sum -c -, echo "5a98fa83fad2edecfd48d18aed2adbd5ceccf6afee1594a3ed3f2e26932dbdbb  scripts/push-changes.sh"
      | sha256sum -c -, echo "d04e32c725b9316805e85d2e8d26d9aaa7010f00e98cd933e4a16c64c0533a6f  scripts/format-and-org-gen.sh"
      | sha256sum -c -, echo "b6ad65e92d1f6f47516586281d55b27794f3bc368d06473781925397f27e7932  scripts/check-formatting.sh"
      | sha256sum -c -, echo "4b2678ee3159c1ee1d4879384163af17d388f0ce1f716bbc6f891e2b32483d3e  scripts/check-org-gen.sh"
      | sha256sum -c -, echo "59e7ec32dc65c1668ca90cb0b825f4d86215cd2b1382babeabaedde8d6d61347  scripts/pre-run.sh"
      | sha256sum -c -, sh scripts/pre-run.sh]
  image: alpine/git:v2.30.1
  name: script-integrity-check
  pull: if-not-exists
- depends_on: [script-integrity-check]
  environment:
    AWS_ACCESS_KEY_ID: {from_secret: aws_access_key_id}
    AWS_SECRET_ACCESS_KEY: {from_secret: aws_secret_access_key}
  image: meltwater/drone-cache
  name: restore-cache
  pull: if-not-exists
  settings:
    archive_format: gzip
    backend: s3
    bucket: heliax-drone-cache-v2
    cache_key: '{{ checksum "stack.yaml" }}'
    mount: [./.stack-work, ./.stack]
    region: eu-west-1
    restore: true
- commands: [make stack-yaml, make test]
  depends_on: [restore-cache]
  image: 965844283396.dkr.ecr.eu-west-1.amazonaws.com/juvix
  name: test-suite
  pull: if-not-exists
- depends_on: [test-suite]
  environment:
    AWS_ACCESS_KEY_ID: {from_secret: aws_access_key_id}
    AWS_SECRET_ACCESS_KEY: {from_secret: aws_secret_access_key}
  image: meltwater/drone-cache
  name: rebuild-cache
  pull: if-not-exists
  settings:
    archive_format: gzip
    backend: s3
    bucket: heliax-drone-cache-v2
    cache_key: '{{ checksum "stack.yaml" }}'
    mount: [./.stack-work, ./.stack]
    override: false
    rebuild: true
    region: eu-west-1
  when:
    status: [success, failure]
- commands: [make test-parser]
  depends_on: [test-suite]
  failure: fast
  image: 965844283396.dkr.ecr.eu-west-1.amazonaws.com/juvix
  name: test-parser
  pull: if-not-exists
- commands: [make test-typecheck]
  depends_on: [test-suite]
  failure: fast
  image: 965844283396.dkr.ecr.eu-west-1.amazonaws.com/juvix
  name: test-typecheck
  pull: if-not-exists
- commands: [make test-compile]
  depends_on: [test-suite]
  failure: fast
  image: 965844283396.dkr.ecr.eu-west-1.amazonaws.com/juvix
  name: test-compile
  pull: if-not-exists
- commands: [sh ./scripts/format-and-org-gen.sh]
  depends_on: [test-typecheck, test-compile, test-parser]
  failure: fast
  image: 965844283396.dkr.ecr.eu-west-1.amazonaws.com/juvix
  name: org-generation-and-code-formatting
  pull: if-not-exists
- commands: [sh ./scripts/push-changes.sh]
  depends_on: [org-generation-and-code-formatting]
  environment:
    GITHUB_TOKEN: {from_secret: github_token}
  image: openanalytics/alpine-git-lfs-client
  name: push changes
  pull: if-not-exists
trigger:
  event: [pull_request]
type: docker
workspace: {path: /drone/workspace}
---
environment: {GIT_LFS_SKIP_SMUDGE: '1', STACK_ROOT: /drone/workspace/.stack}
kind: pipeline
name: juvix-ci-build-push-develop
node: {project: juvix}
steps:
- commands: [echo "e3420e6c66604c53d26292db4a2ba4130d017db1b2e9652d796410e4a9305a04  Makefile"
      | sha256sum -c -, echo "5a98fa83fad2edecfd48d18aed2adbd5ceccf6afee1594a3ed3f2e26932dbdbb  scripts/push-changes.sh"
      | sha256sum -c -, echo "d04e32c725b9316805e85d2e8d26d9aaa7010f00e98cd933e4a16c64c0533a6f  scripts/format-and-org-gen.sh"
      | sha256sum -c -, echo "b6ad65e92d1f6f47516586281d55b27794f3bc368d06473781925397f27e7932  scripts/check-formatting.sh"
      | sha256sum -c -, echo "4b2678ee3159c1ee1d4879384163af17d388f0ce1f716bbc6f891e2b32483d3e  scripts/check-org-gen.sh"
      | sha256sum -c -, echo "59e7ec32dc65c1668ca90cb0b825f4d86215cd2b1382babeabaedde8d6d61347  scripts/pre-run.sh"
      | sha256sum -c -, sh scripts/pre-run.sh]
  image: alpine/git:v2.30.1
  name: script-integrity-check
  pull: if-not-exists
- depends_on: [script-integrity-check]
  environment:
    AWS_ACCESS_KEY_ID: {from_secret: aws_access_key_id}
    AWS_SECRET_ACCESS_KEY: {from_secret: aws_secret_access_key}
  image: meltwater/drone-cache
  name: restore-cache
  pull: if-not-exists
  settings:
    archive_format: gzip
    backend: s3
    bucket: heliax-drone-cache-v2
    cache_key: '{{ checksum "stack.yaml" }}'
    mount: [./.stack-work, ./.stack]
    region: eu-west-1
    restore: true
- commands: [make stack-yaml, make test]
  depends_on: [restore-cache]
  image: 965844283396.dkr.ecr.eu-west-1.amazonaws.com/juvix
  name: test-suite
  pull: if-not-exists
- depends_on: [test-suite]
  environment:
    AWS_ACCESS_KEY_ID: {from_secret: aws_access_key_id}
    AWS_SECRET_ACCESS_KEY: {from_secret: aws_secret_access_key}
  image: meltwater/drone-cache
  name: rebuild-cache
  pull: if-not-exists
  settings:
    archive_format: gzip
    backend: s3
    bucket: heliax-drone-cache-v2
    cache_key: '{{ checksum "stack.yaml" }}'
    mount: [./.stack-work, ./.stack]
    override: false
    rebuild: true
    region: eu-west-1
  when:
    status: [success, failure]
- commands: [sh ./scripts/check-formatting.sh]
  depends_on: [test-suite]
  failure: fast
  image: 965844283396.dkr.ecr.eu-west-1.amazonaws.com/juvix
  name: check-formatting
  pull: if-not-exists
- commands: [sh ./scripts/check-org-gen.sh]
  depends_on: [test-suite]
  failure: fast
  image: 965844283396.dkr.ecr.eu-west-1.amazonaws.com/juvix
  name: check-org-gen
  pull: if-not-exists
- commands: [make test-parser]
  depends_on: [test-suite]
  failure: fast
  image: 965844283396.dkr.ecr.eu-west-1.amazonaws.com/juvix
  name: test-parser
  pull: if-not-exists
- commands: [make test-typecheck]
  depends_on: [test-suite]
  failure: fast
  image: 965844283396.dkr.ecr.eu-west-1.amazonaws.com/juvix
  name: test-typecheck
  pull: if-not-exists
- commands: [make test-compile]
  depends_on: [test-suite]
  failure: fast
  image: 965844283396.dkr.ecr.eu-west-1.amazonaws.com/juvix
  name: test-compile
  pull: if-not-exists
trigger:
  branch: [develop]
  event: [push]
type: docker
workspace: {path: /drone/workspace}
---
kind: signature
hmac: d907afd95d0fe977c1edb3b29d3733c79577eef07e0a160743961094c1a38cb6

...
