name:                juvix-http
version:             0.1.0.0
github:              "anoma/juvix"
license:             GPL-3
author:              "Heliax AG <hello@heliax.dev>"
maintainer:          "Heliax AG <hello@heliax.dev>"
copyright:           "2020 Heliax AG"
description:         Please see the README on GitHub at <https://github.com/githubuser/StandardLibrary#readme>

dependencies:
  - base >= 4.11 && < 5
  - protolude
  - wl-pprint-text
  - hashable
  - capability
  - time
  - mtl
  - lens
  - text
  # Juvix
  - standard-library
  - Sexp
  - frontend
  - core
  - translate
  - michelson
  - Pipeline
  - Context
  - plonk

  # Data Structures
  - containers
  - insert-ordered-containers
  - unordered-containers

  # Serialization
  - cereal
  - aeson

  # Text
  - bytestring
  - text

  # Quickcheck
  - QuickCheck
  - quickcheck-instances
  - generic-random

  # Http
  - wai
  - wai-cors
  - wai-extra
  - warp
  - scientific
  - servant
  - servant-server
  - servant-static-th

# Plonk-specific backend
  - elliptic-curve
  - galois-field

default-extensions:
  - BlockArguments
  - ConstraintKinds
  - DataKinds
  - DefaultSignatures
  - DeriveGeneric
  - FlexibleContexts
  - FlexibleInstances
  - LambdaCase
  - NoImplicitPrelude
  - OverloadedStrings
  - RankNTypes
  - TupleSections
  - TypeApplications
  - TypeFamilies
  - TypeSynonymInstances
  - KindSignatures
  - DefaultSignatures
  - StandaloneDeriving
ghc-options:
  - -ferror-spans
  - -Wall
  - -fno-warn-orphans
  - -fno-warn-name-shadowing
  - -fno-warn-missing-pattern-synonym-signatures
  - -j
  - -static
  - -fwrite-ide-info

# TODO: Specify which packages are exported

when:
  condition: flag(incomplete-error)
  ghc-options:
    - -Werror=incomplete-patterns
    - -Werror=missing-fields
    - -Werror=missing-methods

flags:
  incomplete-error:
    description: >
      Incomplete patterns, missing record fields, and missing class methods are
      an error
    manual: true
    default: false

library:
  source-dirs: src

executables:
  juvix-server:
    main: Main.hs
    source-dirs: src
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - juvix-http


tests:
  http-test:
    main:                Main.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - juvix-http
    - pretty-simple
    - standard-library
    - tasty
    - tasty-hunit
    - tasty-quickcheck
    - tasty-silver
