resolver: lts-18.16

packages:
- .
- ../../StandardLibrary
- ../../Core
- ../../Context
- ../../Pipeline
- ../../Parsing
- ../../Sexp
- ../../Translate
- ../../Test/DataStructures


extra-deps:

########################
# General Dependencies #
########################
- capability-0.4.0.0@sha256:d86d85a1691ef0165c77c47ea72eac75c99d21fb82947efe8b2f758991cf1837,3345
- github: metastatedev/extensible-data
  commit: d11dee6006169cb537e95af28c3541a24194dea8
- github: jyp/prettiest
  commit: e5ce6cd6b4da71860c3d97da84bed4a827fa00ef

################################
# LLVM-HS Library dependencies #
################################
- llvm-hs-pure-9.0.0
- llvm-hs-pretty-0.9.0.0

######################
# Visualizing graphs #
######################
- fgl-visualize-0.1.0.1@sha256:e682066053a6e75478a08fd6822dd0143a3b8ea23244bdb01dd389a266447c5e,995

#########################################################
# Git depdencies caused by Morley specific dependencies #
#########################################################
- git: https://gitlab.com/morley-framework/morley.git
  commit: 6eb73a0cb8d97039d0706aa3f836cc22fe030f96
  subdirs:
    - code/morley
- git: https://gitlab.com/morley-framework/morley.git
  commit: 3584852e68c70cdcf0b346ac9001f8e22f620f35
  subdirs:
    - code/morley-prelude
- base58-bytestring-0.1.0
- hex-text-0.1.0.0
- base16-bytestring-0.1.1.7@sha256:0021256a9628971c08da95cb8f4d0d72192f3bb8a7b30b55c080562d17c43dd3,2231
- show-type-0.1.1
- named-0.3.0.1@sha256:2975d50c9c5d88095026ffc1303d2d9be52e5f588a8f8bcb7003a04b79f10a06,2312
- cryptonite-0.27
- uncaught-exception-0.1.0
- tasty-hunit-compat-0.2.0.1
- with-utf8-1.0.2.2@sha256:42eed140390b3e93d9482b084d1d0150e8774667f39c33bd47e84815751fad09,3057

#########################################################################################
# Git depdencies caused by Morley specific dependencies that are speicific to Michelson #
#########################################################################################
- git: https://github.com/int-index/caps.git
  commit: c5d61837eb358989b581ed82b1e79158c4823b1b
- git: https://github.com/serokell/base-noprelude.git
  commit: 1282e0b992b00089d55228a2aa9edc4a3581c319

######################################################
# Shared Deps Between Arithmetic Circuits and Morley #
######################################################
- git: https://github.com/serokell/elliptic-curve.git
  commit: b8a3d0cf8f7bacfed77dc3b697f5d08bd33396a8
- git: https://github.com/serokell/pairing.git
  commit: cf86cf1f6b03f478a439703b050c520a9d455353
- git: https://github.com/serokell/galois-field.git
  commit: 576ba98ec947370835a1f308895037c7aa7f8b71

###############################
# Stm Containers Dependencies #
###############################
- stm-containers-1.2@sha256:a887f2e7692b7cf20e0b081e2d66e21076e2bd4b57016ec59c484edfa2d29397,3244
- stm-hamt-1.2.0.6@sha256:fba86ccb4b45c5706c19b0e1315ba63dcac3b5d71de945ec001ba921fae80061,3972

#####################################
# Standard Library Extra Dependency #
#####################################
- github: phile314/tasty-silver
  commit: f1f90ac3113cd445e2a7ade43ebb29f0db38ab9b
- tasty-1.4.1@sha256:69e90e965543faf0fc2c8e486d6c1d8cf81fd108e2c4541234c41490f392f94f,2638


allow-newer: true