resolver: lts-17.9

packages:
- .
- ../../StandardLibrary
- ../../Core

extra-deps:

########################
# General Dependencies #
########################
- capability-0.4.0.0@sha256:d86d85a1691ef0165c77c47ea72eac75c99d21fb82947efe8b2f758991cf1837,3345
- github: metastatedev/extensible-data
  commit: d11dee6006169cb537e95af28c3541a24194dea8
- github: jyp/prettiest
  commit: e5ce6cd6b4da71860c3d97da84bed4a827fa00ef

#####################################
# Standard Library Extra Dependency #
#####################################
- github: phile314/tasty-silver
  commit: f1f90ac3113cd445e2a7ade43ebb29f0db38ab9b
- tasty-1.4.1@sha256:69e90e965543faf0fc2c8e486d6c1d8cf81fd108e2c4541234c41490f392f94f,2638

####################################
# For Interaction Nets json-schema #
####################################
- github: cryptiumlabs/jsonschema-gen
  commit: 0639cd166ec59a04d07a3a7d49bdf343e567000e

######################
# Visualizing graphs #
######################
- fgl-visualize-0.1.0.1@sha256:e682066053a6e75478a08fd6822dd0143a3b8ea23244bdb01dd389a266447c5e,995

######################
# For the EAC Solver #
######################
- github: cwgoes/haskell-z3
  commit: 889597234bcdf5620c5a69d3405ab4d607ba4d71


allow-newer: true